export const pricingPlansData = [
  {
    name: "Starter",
    monthlyPrice: 19,
    annualPrice: 190,
    features: [
      "Up to 20 invoices/month",
      "2 user accounts",
      "Email support",
      "Basic analytics",
      "PDF invoice generation",
      "Single tenant",
    ],
    cta: "Start Free Trial",
  },
  {
    name: "Professional",
    popular: true,
    monthlyPrice: 49,
    annualPrice: 490,
    features: [
      "Unlimited invoices",
      "10 user accounts",
      "Priority support",
      "Advanced analytics & reporting",
      "Custom invoice templates",
      "Up to 3 tenants",
      "Automated reminders",
      "Client portal",
    ],
    cta: "Start Free Trial",
  },
  {
    name: "Enterprise",
    monthlyPrice: 99,
    annualPrice: 990,
    features: [
      "Everything in Professional",
      "Unlimited user accounts",
      "Dedicated support manager",
      "Custom integrations",
      "API access",
      "Unlimited tenants",
      "Advanced security features",
      "White-labeling options",
    ],
    cta: "Contact Sales",
  },
];